Numpy Exercises

In [ ]:
1-Array datatype conversion

In [2]:
import numpy as np

In [9]:
a=np.array([[1,2,3],[4,5,6]])

In [10]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
a.astype("float")

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
2-Array re-dimensioning

In [13]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [8]:
3-Element-wise addition of 2 numpy arrays

In [3]:
b = np.array([[1,2,3],
              [4,5,6]])

c = np.array([[10,11,12],
              [13,14,15]])

In [4]:
d=b+c

In [5]:
d

array([[11, 13, 15],
       [17, 19, 21]])

In [ ]:
4-Multipying matrix by a scalar 

In [6]:
a = np.array([[1,2,3],
              [4,5,6]])

In [7]:
a=a*3
a

array([[ 3,  6,  9],
       [12, 15, 18]])

In [ ]:
5-Identity Matrix

In [9]:
i = np.eye(5)
print(i)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


6-Binary array to boolean array

In [11]:
e = np.array([[1, 0, 0],
              [1, 0, 1],
              [1, 0, 1]])

In [12]:
o = e.astype('bool')
print(o)

[[ True False False]
 [ True False  True]
 [ True False  True]]


In [ ]:
7-Horizontal Stacking of Numpy Arrays

In [14]:
a=np.array([[1,2,3],
           [4,5,6]])
b=np.array([[7,8,9],
          [10,11,12]])


In [18]:
c=np.hstack((a,b))
c

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
8-Vertically Stacking of Numpy Arrays

In [19]:
a=np.array([[1,2],
            [3,4],
            [5,6]])
b=np.array([[7,8],
            [9,10],
            [11,12]])


In [21]:
c=np.vstack((a,b))
c

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
9- 0 to 100 increments of two

In [23]:
a=np.arange(0,101,2)
print(a)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [28]:
a=[i for i in range(0,101,2)]
a=np.array(a)
print(a)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [ ]:
10-From 2 numpy arrays, extract the indexes in which the elements in the 2 arrays match

In [30]:
a=np.array([1,2,3,4,5])
b=np.array([2,3,4,4,5])
print(np.where(a==b))

(array([3, 4], dtype=int64),)


In [ ]:
11-Matrix Transpose

In [31]:
a=np.array([[1,2,3],
           [4,5,6],
           [7,8,9]])
a=a.T
print(a)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
12-0 to 100(both inclusive) equally gapped 5 numbers in the range

In [32]:
a=np.linspace(0,100,5)
print(a)

[  0.  25.  50.  75. 100.]


In [ ]:
13- 2 dimensions array, 5 times

In [34]:
a=np.array([[1,2,3],
            [4,5,6]])
a=np.tile(a,5)
a

array([[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6]])

In [ ]:
14- 3 by 3 matrix of random numbers normal distribution

In [35]:
b=np.random.normal(size=(3,3))
b

array([[-1.14310615, -0.2997285 ,  0.26427914],
       [ 1.03166464,  0.14584596, -1.07303385],
       [ 2.19844288, -1.66495595,  1.43441901]])

In [ ]:
15- matrix multiplication

In [38]:
a=np.array([[1,2],
           [3,5]])

b=np.array([[4,5],
             [1,2]])

c=np.matmul(a,b)
c

array([[ 6,  9],
       [17, 25]])

In [39]:
a=np.array([[1,2],
           [3,5]])

b=np.array([[4,5],
             [1,2]])

c=a@b
c

array([[ 6,  9],
       [17, 25]])

In [ ]:
16- array element sort

In [42]:
a=np.array([1,8,2,9,3,6,5])
a=np.sort(a)
a

array([1, 2, 3, 5, 6, 8, 9])

In [ ]:
17-array element index sorting

In [43]:
a=np.array([1,8,2,9,3,6,5])
a=np.argsort(a)
#before sorting 1,2,3,5,6,8,9
#       index:  0,2,4,6,5,1,3
a

array([0, 2, 4, 6, 5, 1, 3], dtype=int64)

In [ ]:
18- 4 by 4 matrix random int in 0 to 10

In [45]:
a=np.random.randint(0,10,size=(4,4))
a

array([[6, 8, 3, 0],
       [3, 0, 6, 5],
       [8, 0, 3, 4],
       [1, 7, 0, 5]])

In [ ]:
19- 4 by 6 matrix with every value equal 4

In [46]:
a=np.full((4,6),4)
a

array([[4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4]])

In [49]:
a=np.ones((4,6))
a=a*4
print(a)

[[4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4.]]
